name: Main CI-pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkstyle
        run: make check_fmt
 
      - name: Test
        run: make test

      - name: Install valgrind
        run: |
          if ! command -v valgrind > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y valgrind
          fi

      - name: Valgrind memory check
        run: make valgrind
